const express = require('express');
const router = express.Router();

// القائمة الأساسية (fallback) — تظهر إذا كانت collection فاضية، بنفس نمط restaurants.js
const defaultMartProducts = [
  {
    "id": "d_1",
    "categoryId": "dairy",
    "nameAr": "حليب الجنيدي 3% دسم 1 لتر",
    "nameEn": "Al-Juneidi Milk 3% 1L",
    "unitAr": "1 لتر",
    "unitEn": "1 Liter",
    "price": 7.0,
    "marketPrice": 7.0,
    "emoji": "🥛",
    "imageUrl": "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "d_2",
    "categoryId": "dairy",
    "nameAr": "حليب الريان طازج 1 لتر",
    "nameEn": "Al-Rayan Milk 1L",
    "unitAr": "1 لتر",
    "unitEn": "1 Liter",
    "price": 6.5,
    "marketPrice": 6.5,
    "emoji": "🥛",
    "imageUrl": "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "d_3",
    "categoryId": "dairy",
    "nameAr": "حليب بينار كامل الدسم 1 لتر",
    "nameEn": "Pinar Full Cream Milk 1L",
    "unitAr": "1 لتر",
    "unitEn": "1 Liter",
    "price": 7.5,
    "marketPrice": 7.5,
    "emoji": "🥛",
    "imageUrl": "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "d_4",
    "categoryId": "dairy",
    "nameAr": "لبن رائب حمودة 1 كغم",
    "nameEn": "Hammoudeh Yogurt 1kg",
    "unitAr": "1 كغم",
    "unitEn": "1 kg",
    "price": 8.5,
    "marketPrice": 8.5,
    "emoji": "🥣",
    "imageUrl": "https://images.unsplash.com/photo-1571212515416-fef01fc43637?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "d_5",
    "categoryId": "dairy",
    "nameAr": "لبن رائب الريان 1 كغم",
    "nameEn": "Al-Rayan Yogurt 1kg",
    "unitAr": "1 كغم",
    "unitEn": "1 kg",
    "price": 9.0,
    "marketPrice": 9.0,
    "emoji": "🥣",
    "imageUrl": "https://images.unsplash.com/photo-1571212515416-fef01fc43637?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "d_6",
    "categoryId": "dairy",
    "nameAr": "لبنة حمودة 500 غرام",
    "nameEn": "Hammoudeh Labneh 500g",
    "unitAr": "500 غرام",
    "unitEn": "500g",
    "price": 11.0,
    "marketPrice": 11.0,
    "emoji": "🥣",
    "imageUrl": "https://images.unsplash.com/photo-1571212515416-fef01fc43637?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "d_7",
    "categoryId": "dairy",
    "nameAr": "لبنة كرتون بلدي 400 غرام",
    "nameEn": "Local Carton Labneh 400g",
    "unitAr": "400 غرام",
    "unitEn": "400g",
    "price": 9.5,
    "marketPrice": 9.5,
    "emoji": "🥣",
    "imageUrl": "https://images.unsplash.com/photo-1571212515416-fef01fc43637?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "d_8",
    "categoryId": "dairy",
    "nameAr": "قشطة صفا 250 غرام",
    "nameEn": "Safa Cream 250g",
    "unitAr": "250 غرام",
    "unitEn": "250g",
    "price": 9.5,
    "marketPrice": 9.5,
    "emoji": "🥣",
    "imageUrl": "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "d_9",
    "categoryId": "dairy",
    "nameAr": "قشطة بوك 170 غرام",
    "nameEn": "Puck Cream 170g",
    "unitAr": "170 غرام",
    "unitEn": "170g",
    "price": 4.5,
    "marketPrice": 4.5,
    "emoji": "🥣",
    "imageUrl": "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "d_10",
    "categoryId": "dairy",
    "nameAr": "كريمة طبخ بوك 500 مل",
    "nameEn": "Puck Cooking Cream 500ml",
    "unitAr": "500 مل",
    "unitEn": "500ml",
    "price": 14.5,
    "marketPrice": 14.5,
    "emoji": "🥛",
    "imageUrl": "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "d_11",
    "categoryId": "dairy",
    "nameAr": "زبدة لورباك 200 غرام",
    "nameEn": "Lurpak Butter 200g",
    "unitAr": "200 غرام",
    "unitEn": "200g",
    "price": 12.5,
    "marketPrice": 12.5,
    "emoji": "🧈",
    "imageUrl": "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "d_12",
    "categoryId": "dairy",
    "nameAr": "زبدة المراعي 200 غرام",
    "nameEn": "Almarai Butter 200g",
    "unitAr": "200 غرام",
    "unitEn": "200g",
    "price": 11.0,
    "marketPrice": 11.0,
    "emoji": "🧈",
    "imageUrl": "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "ch_1",
    "categoryId": "dairy",
    "nameAr": "جبنة نابلسية بلدية 1 كغم",
    "nameEn": "Nabulsi Cheese 1kg",
    "unitAr": "1 كغم",
    "unitEn": "1 kg",
    "price": 35.0,
    "marketPrice": 35.0,
    "emoji": "🧀",
    "imageUrl": "https://images.unsplash.com/photo-1552767059-ce182ead6c1b?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "ch_2",
    "categoryId": "dairy",
    "nameAr": "جبنة كشكوان طوبا 500 غرام",
    "nameEn": "Tuba Kashkaval 500g",
    "unitAr": "500 غرام",
    "unitEn": "500g",
    "price": 24.0,
    "marketPrice": 24.0,
    "emoji": "🧀",
    "imageUrl": "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "ch_3",
    "categoryId": "dairy",
    "nameAr": "جبنة حلوم 250 غرام",
    "nameEn": "Halloumi Cheese 250g",
    "unitAr": "250 غرام",
    "unitEn": "250g",
    "price": 14.0,
    "marketPrice": 14.0,
    "emoji": "🧀",
    "imageUrl": "https://images.unsplash.com/photo-1552767059-ce182ead6c1b?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "ch_4",
    "categoryId": "dairy",
    "nameAr": "جبنة مثلثات المراعي 24 قطعة",
    "nameEn": "Almarai Triangles 24pcs",
    "unitAr": "24 قطعة",
    "unitEn": "24pcs",
    "price": 16.5,
    "marketPrice": 16.5,
    "emoji": "🧀",
    "imageUrl": "https://images.unsplash.com/photo-1552767059-ce182ead6c1b?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "ch_5",
    "categoryId": "dairy",
    "nameAr": "جبنة مثلثات البقرة الضاحكة 16 قطعة",
    "nameEn": "La Vache Qui Rit 16pcs",
    "unitAr": "16 قطعة",
    "unitEn": "16pcs",
    "price": 12.0,
    "marketPrice": 12.0,
    "emoji": "🧀",
    "imageUrl": "https://images.unsplash.com/photo-1552767059-ce182ead6c1b?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "ch_6",
    "categoryId": "dairy",
    "nameAr": "جبنة كاسات كرافت 480 غرام",
    "nameEn": "Kraft Spread 480g",
    "unitAr": "480 غرام",
    "unitEn": "480g",
    "price": 19.0,
    "marketPrice": 19.0,
    "emoji": "🧀",
    "imageUrl": "https://images.unsplash.com/photo-1552767059-ce182ead6c1b?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "ch_7",
    "categoryId": "dairy",
    "nameAr": "جبنة كاسات بوك 500 غرام",
    "nameEn": "Puck Spread 500g",
    "unitAr": "500 غرام",
    "unitEn": "500g",
    "price": 18.0,
    "marketPrice": 18.0,
    "emoji": "🧀",
    "imageUrl": "https://images.unsplash.com/photo-1552767059-ce182ead6c1b?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "ch_8",
    "categoryId": "dairy",
    "nameAr": "جبنة موزاريلا مبشورة 500 غرام",
    "nameEn": "Shredded Mozzarella 500g",
    "unitAr": "500 غرام",
    "unitEn": "500g",
    "price": 21.0,
    "marketPrice": 21.0,
    "emoji": "🧀",
    "imageUrl": "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "ch_9",
    "categoryId": "dairy",
    "nameAr": "جبنة شيدر شرائح 200 غرام",
    "nameEn": "Sliced Cheddar 200g",
    "unitAr": "200 غرام",
    "unitEn": "200g",
    "price": 11.5,
    "marketPrice": 11.5,
    "emoji": "🧀",
    "imageUrl": "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "ch_10",
    "categoryId": "dairy",
    "nameAr": "جبنة فيتا طازجة 500 غرام",
    "nameEn": "Fresh Feta 500g",
    "unitAr": "500 غرام",
    "unitEn": "500g",
    "price": 13.0,
    "marketPrice": 13.0,
    "emoji": "🧀",
    "imageUrl": "https://images.unsplash.com/photo-1552767059-ce182ead6c1b?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "v_1",
    "categoryId": "veggies",
    "nameAr": "تفاح أحمر 1 كغم",
    "nameEn": "Red Apples 1kg",
    "unitAr": "1 كغم",
    "unitEn": "1 kg",
    "price": 9.0,
    "marketPrice": 9.0,
    "emoji": "🍎",
    "imageUrl": "https://images.unsplash.com/photo-1560806887-1e4cd0b6fac6?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "v_2",
    "categoryId": "veggies",
    "nameAr": "تفاح أصفر 1 كغم",
    "nameEn": "Yellow Apples 1kg",
    "unitAr": "1 كغم",
    "unitEn": "1 kg",
    "price": 8.5,
    "marketPrice": 8.5,
    "emoji": "🍏",
    "imageUrl": "https://images.unsplash.com/photo-1560806887-1e4cd0b6fac6?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "v_3",
    "categoryId": "veggies",
    "nameAr": "موز أريحا 1 كغم",
    "nameEn": "Jericho Bananas 1kg",
    "unitAr": "1 كغم",
    "unitEn": "1 kg",
    "price": 6.0,
    "marketPrice": 6.0,
    "emoji": "🍌",
    "imageUrl": "https://images.unsplash.com/photo-1481349518771-20055b2a7b24?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "v_4",
    "categoryId": "veggies",
    "nameAr": "خيار بلدي 1 كغم",
    "nameEn": "Cucumbers 1kg",
    "unitAr": "1 كغم",
    "unitEn": "1 kg",
    "price": 4.5,
    "marketPrice": 4.5,
    "emoji": "🥒",
    "imageUrl": "https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "v_5",
    "categoryId": "veggies",
    "nameAr": "بندورة حمراء 1 كغم",
    "nameEn": "Tomatoes 1kg",
    "unitAr": "1 كغم",
    "unitEn": "1 kg",
    "price": 5.0,
    "marketPrice": 5.0,
    "emoji": "🍅",
    "imageUrl": "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "v_6",
    "categoryId": "veggies",
    "nameAr": "بطاطا بلدي 1 كغم",
    "nameEn": "Potatoes 1kg",
    "unitAr": "1 كغم",
    "unitEn": "1 kg",
    "price": 4.0,
    "marketPrice": 4.0,
    "emoji": "🥔",
    "imageUrl": "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "v_7",
    "categoryId": "veggies",
    "nameAr": "بصل ناشف 1 كغم",
    "nameEn": "Onions 1kg",
    "unitAr": "1 كغم",
    "unitEn": "1 kg",
    "price": 3.5,
    "marketPrice": 3.5,
    "emoji": "🧅",
    "imageUrl": "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "v_8",
    "categoryId": "veggies",
    "nameAr": "ليمون بلدي 1 كغم",
    "nameEn": "Lemons 1kg",
    "unitAr": "1 كغم",
    "unitEn": "1 kg",
    "price": 6.5,
    "marketPrice": 6.5,
    "emoji": "🍋",
    "imageUrl": "https://images.unsplash.com/photo-1534531141161-e41d133a4b97?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "v_9",
    "categoryId": "veggies",
    "nameAr": "برتقال أبو صرة 1 كغم",
    "nameEn": "Navel Oranges 1kg",
    "unitAr": "1 كغم",
    "unitEn": "1 kg",
    "price": 5.5,
    "marketPrice": 5.5,
    "emoji": "🍊",
    "imageUrl": "https://images.unsplash.com/photo-1613478223719-2ab802602423?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "v_10",
    "categoryId": "veggies",
    "nameAr": "خس بلدي رأس واحد",
    "nameEn": "Lettuce Head",
    "unitAr": "رأس واحد",
    "unitEn": "1 Head",
    "price": 3.0,
    "marketPrice": 3.0,
    "emoji": "🥬",
    "imageUrl": "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "v_11",
    "categoryId": "veggies",
    "nameAr": "فلفل حلو مشكل 1 كغم",
    "nameEn": "Sweet Peppers 1kg",
    "unitAr": "1 كغم",
    "unitEn": "1 kg",
    "price": 7.5,
    "marketPrice": 7.5,
    "emoji": "🫑",
    "imageUrl": "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "v_12",
    "categoryId": "veggies",
    "nameAr": "طبق بيض بلدي 30 حبة",
    "nameEn": "Egg Carton 30pcs",
    "unitAr": "30 حبة",
    "unitEn": "30pcs",
    "price": 18.0,
    "marketPrice": 18.0,
    "emoji": "🥚",
    "imageUrl": "https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "v_13",
    "categoryId": "veggies",
    "nameAr": "ثوم ناشف 500 غرام",
    "nameEn": "Garlic 500g",
    "unitAr": "500 غرام",
    "unitEn": "500g",
    "price": 8.0,
    "marketPrice": 8.0,
    "emoji": "🧄",
    "imageUrl": "https://images.unsplash.com/photo-1540148426945-6cf22a6b2383?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "v_14",
    "categoryId": "veggies",
    "nameAr": "جزر بلدي 1 كغم",
    "nameEn": "Carrots 1kg",
    "unitAr": "1 كغم",
    "unitEn": "1 kg",
    "price": 5.0,
    "marketPrice": 5.0,
    "emoji": "🥕",
    "imageUrl": "https://images.unsplash.com/photo-1447175008436-08417192978d?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "sn_1",
    "categoryId": "snacks",
    "nameAr": "شوكولاتة جالكسي بالحليب 90 غرام",
    "nameEn": "Galaxy Milk Chocolate 90g",
    "unitAr": "90 غرام",
    "unitEn": "90g",
    "price": 5.5,
    "marketPrice": 5.5,
    "emoji": "🍫",
    "imageUrl": "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "sn_2",
    "categoryId": "snacks",
    "nameAr": "شوكولاتة جالكسي بالمكسرات 90 غرام",
    "nameEn": "Galaxy Hazelnut 90g",
    "unitAr": "90 غرام",
    "unitEn": "90g",
    "price": 5.5,
    "marketPrice": 5.5,
    "emoji": "🍫",
    "imageUrl": "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "sn_3",
    "categoryId": "snacks",
    "nameAr": "شوكولاتة نوتيلا 400 غرام",
    "nameEn": "Nutella 400g",
    "unitAr": "400 غرام",
    "unitEn": "400g",
    "price": 20.0,
    "marketPrice": 20.0,
    "emoji": "🍫",
    "imageUrl": "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "sn_4",
    "categoryId": "snacks",
    "nameAr": "شوكولاتة كيت كات 4 أصابع",
    "nameEn": "KitKat 4 Finger",
    "unitAr": "41.5 غرام",
    "unitEn": "41.5g",
    "price": 3.5,
    "marketPrice": 3.5,
    "emoji": "🍫",
    "imageUrl": "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "sn_5",
    "categoryId": "snacks",
    "nameAr": "شوكولاتة كيت كات تشانكي",
    "nameEn": "KitKat Chunky",
    "unitAr": "40 غرام",
    "unitEn": "40g",
    "price": 3.5,
    "marketPrice": 3.5,
    "emoji": "🍫",
    "imageUrl": "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "sn_6",
    "categoryId": "snacks",
    "nameAr": "شوكولاتة سنكرز 50 غرام",
    "nameEn": "Snickers 50g",
    "unitAr": "50 غرام",
    "unitEn": "50g",
    "price": 3.5,
    "marketPrice": 3.5,
    "emoji": "🍫",
    "imageUrl": "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "sn_7",
    "categoryId": "snacks",
    "nameAr": "شوكولاتة مارس 51 غرام",
    "nameEn": "Mars Bar 51g",
    "unitAr": "51 غرام",
    "unitEn": "51g",
    "price": 3.5,
    "marketPrice": 3.5,
    "emoji": "🍫",
    "imageUrl": "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "sn_8",
    "categoryId": "snacks",
    "nameAr": "شوكولاتة باونتي 57 غرام",
    "nameEn": "Bounty 57g",
    "unitAr": "57 غرام",
    "unitEn": "57g",
    "price": 3.5,
    "marketPrice": 3.5,
    "emoji": "🍫",
    "imageUrl": "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "sn_9",
    "categoryId": "snacks",
    "nameAr": "شوكولاتة تويكس 50 غرام",
    "nameEn": "Twix 50g",
    "unitAr": "50 غرام",
    "unitEn": "50g",
    "price": 3.5,
    "marketPrice": 3.5,
    "emoji": "🍫",
    "imageUrl": "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "sn_10",
    "categoryId": "snacks",
    "nameAr": "شوكولاتة كندر بوينو 43 غرام",
    "nameEn": "Kinder Bueno 43g",
    "unitAr": "43 غرام",
    "unitEn": "43g",
    "price": 4.5,
    "marketPrice": 4.5,
    "emoji": "🍫",
    "imageUrl": "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "sn_11",
    "categoryId": "snacks",
    "nameAr": "شوكولاتة فريرو روشيه 16 قطعة",
    "nameEn": "Ferrero Rocher 16pcs",
    "unitAr": "16 قطعة",
    "unitEn": "16pcs",
    "price": 32.0,
    "marketPrice": 32.0,
    "emoji": "🍫",
    "imageUrl": "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "sn_12",
    "categoryId": "snacks",
    "nameAr": "بسكويت أوريو 6 قطع",
    "nameEn": "Oreo 6 Pack",
    "unitAr": "6 قطع",
    "unitEn": "6 Pack",
    "price": 4.5,
    "marketPrice": 4.5,
    "emoji": "🍪",
    "imageUrl": "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "sn_13",
    "categoryId": "snacks",
    "nameAr": "بسكويت لوتس بيسكوف 250 غرام",
    "nameEn": "Lotus Biscoff 250g",
    "unitAr": "250 غرام",
    "unitEn": "250g",
    "price": 12.0,
    "marketPrice": 12.0,
    "emoji": "🍪",
    "imageUrl": "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "sn_14",
    "categoryId": "snacks",
    "nameAr": "ويفر لواكر كوادراتيني 125 غرام",
    "nameEn": "Loacker Quadratini 125g",
    "unitAr": "125 غرام",
    "unitEn": "125g",
    "price": 9.5,
    "marketPrice": 9.5,
    "emoji": "🧇",
    "imageUrl": "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "cp_1",
    "categoryId": "snacks",
    "nameAr": "شيبس ليز بالملح 170 غرام",
    "nameEn": "Lay's Salt Chips 170g",
    "unitAr": "170 غرام",
    "unitEn": "170g",
    "price": 7.5,
    "marketPrice": 7.5,
    "emoji": "🥔",
    "imageUrl": "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "cp_2",
    "categoryId": "snacks",
    "nameAr": "شيبس ليز بالخل والملح 170 غرام",
    "nameEn": "Lay's Salt & Vinegar 170g",
    "unitAr": "170 غرام",
    "unitEn": "170g",
    "price": 7.5,
    "marketPrice": 7.5,
    "emoji": "🥔",
    "imageUrl": "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "cp_3",
    "categoryId": "snacks",
    "nameAr": "شيبس ليز بالجبنة الفرنسية 170 غرام",
    "nameEn": "Lay's Cheese 170g",
    "unitAr": "170 غرام",
    "unitEn": "170g",
    "price": 7.5,
    "marketPrice": 7.5,
    "emoji": "🥔",
    "imageUrl": "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "cp_4",
    "categoryId": "snacks",
    "nameAr": "شيبس دوريتوس ناتشو 180 غرام",
    "nameEn": "Doritos Nacho Cheese 180g",
    "unitAr": "180 غرام",
    "unitEn": "180g",
    "price": 7.5,
    "marketPrice": 7.5,
    "emoji": "🌽",
    "imageUrl": "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "cp_5",
    "categoryId": "snacks",
    "nameAr": "شيبس دوريتوس حار حلو 180 غرام",
    "nameEn": "Doritos Sweet Chili 180g",
    "unitAr": "180 غرام",
    "unitEn": "180g",
    "price": 7.5,
    "marketPrice": 7.5,
    "emoji": "🌽",
    "imageUrl": "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "cp_6",
    "categoryId": "snacks",
    "nameAr": "شيبس برينجلز أصلي 165 غرام",
    "nameEn": "Pringles Original 165g",
    "unitAr": "165 غرام",
    "unitEn": "165g",
    "price": 10.5,
    "marketPrice": 10.5,
    "emoji": "🥔",
    "imageUrl": "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "cp_7",
    "categoryId": "snacks",
    "nameAr": "شيبس برينجلز بالجبنة 165 غرام",
    "nameEn": "Pringles Cheese 165g",
    "unitAr": "165 غرام",
    "unitEn": "165g",
    "price": 10.5,
    "marketPrice": 10.5,
    "emoji": "🥔",
    "imageUrl": "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "cp_8",
    "categoryId": "snacks",
    "nameAr": "شيبس شيتوس كرنشي بالجبنة 150 غرام",
    "nameEn": "Cheetos Crunchy Cheese 150g",
    "unitAr": "150 غرام",
    "unitEn": "150g",
    "price": 7.0,
    "marketPrice": 7.0,
    "emoji": "🌽",
    "imageUrl": "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "cp_9",
    "categoryId": "snacks",
    "nameAr": "مكسرات مشكلة محمصة 250 غرام",
    "nameEn": "Mixed Roasted Nuts 250g",
    "unitAr": "250 غرام",
    "unitEn": "250g",
    "price": 20.0,
    "marketPrice": 20.0,
    "emoji": "🥜",
    "imageUrl": "https://images.unsplash.com/photo-1536591375315-19895658238f?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "cp_10",
    "categoryId": "snacks",
    "nameAr": "فستق سوداني مملح 200 غرام",
    "nameEn": "Salted Peanuts 200g",
    "unitAr": "200 غرام",
    "unitEn": "200g",
    "price": 7.0,
    "marketPrice": 7.0,
    "emoji": "🥜",
    "imageUrl": "https://images.unsplash.com/photo-1536591375315-19895658238f?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "dr_1",
    "categoryId": "drinks",
    "nameAr": "كوكاكولا 1.5 لتر",
    "nameEn": "Coca-Cola 1.5L",
    "unitAr": "1.5 لتر",
    "unitEn": "1.5 Liter",
    "price": 7.0,
    "marketPrice": 7.0,
    "emoji": "🥤",
    "imageUrl": "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "dr_2",
    "categoryId": "drinks",
    "nameAr": "كوكاكولا كان 330 مل",
    "nameEn": "Coca-Cola Can 330ml",
    "unitAr": "330 مل",
    "unitEn": "330ml",
    "price": 3.0,
    "marketPrice": 3.0,
    "emoji": "🥤",
    "imageUrl": "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "dr_3",
    "categoryId": "drinks",
    "nameAr": "كوكاكولا زيرو 1.5 لتر",
    "nameEn": "Coca-Cola Zero 1.5L",
    "unitAr": "1.5 لتر",
    "unitEn": "1.5 Liter",
    "price": 7.0,
    "marketPrice": 7.0,
    "emoji": "🥤",
    "imageUrl": "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "dr_4",
    "categoryId": "drinks",
    "nameAr": "سبريت 1.5 لتر",
    "nameEn": "Sprite 1.5L",
    "unitAr": "1.5 لتر",
    "unitEn": "1.5 Liter",
    "price": 7.0,
    "marketPrice": 7.0,
    "emoji": "🥤",
    "imageUrl": "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "dr_5",
    "categoryId": "drinks",
    "nameAr": "فانتا برتقال 1.5 لتر",
    "nameEn": "Fanta Orange 1.5L",
    "unitAr": "1.5 لتر",
    "unitEn": "1.5 Liter",
    "price": 7.0,
    "marketPrice": 7.0,
    "emoji": "🥤",
    "imageUrl": "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "dr_6",
    "categoryId": "drinks",
    "nameAr": "عصير سيزار برتقال 1 لتر",
    "nameEn": "Cesar Orange Juice 1L",
    "unitAr": "1 لتر",
    "unitEn": "1 Liter",
    "price": 9.5,
    "marketPrice": 9.5,
    "emoji": "🍊",
    "imageUrl": "https://images.unsplash.com/photo-1613478223719-2ab802602423?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "dr_7",
    "categoryId": "drinks",
    "nameAr": "عصير سيزار تفاح 1 لتر",
    "nameEn": "Cesar Apple Juice 1L",
    "unitAr": "1 لتر",
    "unitEn": "1 Liter",
    "price": 9.5,
    "marketPrice": 9.5,
    "emoji": "🧃",
    "imageUrl": "https://images.unsplash.com/photo-1613478223719-2ab802602423?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "dr_8",
    "categoryId": "drinks",
    "nameAr": "عصير الربيع برتقال 1 لتر",
    "nameEn": "Al-Rabie Orange 1L",
    "unitAr": "1 لتر",
    "unitEn": "1 Liter",
    "price": 8.5,
    "marketPrice": 8.5,
    "emoji": "🍊",
    "imageUrl": "https://images.unsplash.com/photo-1613478223719-2ab802602423?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "dr_9",
    "categoryId": "drinks",
    "nameAr": "عصير راني خوخ 240 مل",
    "nameEn": "Rani Peach 240ml",
    "unitAr": "240 مل",
    "unitEn": "240ml",
    "price": 4.0,
    "marketPrice": 4.0,
    "emoji": "🍑",
    "imageUrl": "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "dr_10",
    "categoryId": "drinks",
    "nameAr": "عصير راني مانجو 240 مل",
    "nameEn": "Rani Mango 240ml",
    "unitAr": "240 مل",
    "unitEn": "240ml",
    "price": 4.0,
    "marketPrice": 4.0,
    "emoji": "🥭",
    "imageUrl": "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "dr_11",
    "categoryId": "drinks",
    "nameAr": "ريدبول 250 مل",
    "nameEn": "Red Bull 250ml",
    "unitAr": "250 مل",
    "unitEn": "250ml",
    "price": 9.5,
    "marketPrice": 9.5,
    "emoji": "⚡",
    "imageUrl": "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "dr_12",
    "categoryId": "drinks",
    "nameAr": "مياه أروى 6*1.5 لتر",
    "nameEn": "Arwa Water 6x1.5L",
    "unitAr": "6 حبات",
    "unitEn": "Pack 6",
    "price": 12.0,
    "marketPrice": 12.0,
    "emoji": "💧",
    "imageUrl": "https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "dr_13",
    "categoryId": "drinks",
    "nameAr": "قهوة بن العميد 250 غرام",
    "nameEn": "Al-Ameed Coffee 250g",
    "unitAr": "250 غرام",
    "unitEn": "250g",
    "price": 16.0,
    "marketPrice": 16.0,
    "emoji": "☕",
    "imageUrl": "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "dr_14",
    "categoryId": "drinks",
    "nameAr": "نسكافيه جولد 200 غرام",
    "nameEn": "Nescafe Gold 200g",
    "unitAr": "200 غرام",
    "unitEn": "200g",
    "price": 38.0,
    "marketPrice": 38.0,
    "emoji": "☕",
    "imageUrl": "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "bk_1",
    "categoryId": "bakery",
    "nameAr": "خبز صمون 8 حبات",
    "nameEn": "Samoon Bread 8pcs",
    "unitAr": "8 حبات",
    "unitEn": "8pcs",
    "price": 5.0,
    "marketPrice": 5.0,
    "emoji": "🥖",
    "imageUrl": "https://images.unsplash.com/photo-1598373182133-52452f7691ef?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "bk_2",
    "categoryId": "bakery",
    "nameAr": "خبز توست لوزين 500 غرام",
    "nameEn": "Lusine Toast 500g",
    "unitAr": "500 غرام",
    "unitEn": "500g",
    "price": 7.0,
    "marketPrice": 7.0,
    "emoji": "🍞",
    "imageUrl": "https://images.unsplash.com/photo-1598373182133-52452f7691ef?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "bk_3",
    "categoryId": "bakery",
    "nameAr": "خبز كماج بلدي 1 كغم",
    "nameEn": "Local Pita 1kg",
    "unitAr": "1 كغم",
    "unitEn": "1 kg",
    "price": 5.0,
    "marketPrice": 5.0,
    "emoji": "🫓",
    "imageUrl": "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "bk_4",
    "categoryId": "bakery",
    "nameAr": "طحين مطاحن نابلس 1 كغم",
    "nameEn": "Nablus Flour 1kg",
    "unitAr": "1 كغم",
    "unitEn": "1 kg",
    "price": 5.0,
    "marketPrice": 5.0,
    "emoji": "🌾",
    "imageUrl": "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "bk_5",
    "categoryId": "bakery",
    "nameAr": "سكر أبيض ناعم 1 كغم",
    "nameEn": "White Sugar 1kg",
    "unitAr": "1 كغم",
    "unitEn": "1 kg",
    "price": 4.5,
    "marketPrice": 4.5,
    "emoji": "🍚",
    "imageUrl": "https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "bk_6",
    "categoryId": "bakery",
    "nameAr": "ملح طعام ساسا 700 غرام",
    "nameEn": "Sasa Salt 700g",
    "unitAr": "700 غرام",
    "unitEn": "700g",
    "price": 2.5,
    "marketPrice": 2.5,
    "emoji": "🧂",
    "imageUrl": "https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "bk_7",
    "categoryId": "bakery",
    "nameAr": "أرز صنوايت 1 كغم",
    "nameEn": "Sunwhite Rice 1kg",
    "unitAr": "1 كغم",
    "unitEn": "1 kg",
    "price": 9.0,
    "marketPrice": 9.0,
    "emoji": "🍚",
    "imageUrl": "https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "bk_8",
    "categoryId": "bakery",
    "nameAr": "أرز بسمتي المحمود 5 كغم",
    "nameEn": "Al-Mahmoud Basmati 5kg",
    "unitAr": "5 كغم",
    "unitEn": "5 kg",
    "price": 48.0,
    "marketPrice": 48.0,
    "emoji": "🍚",
    "imageUrl": "https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "bk_9",
    "categoryId": "bakery",
    "nameAr": "معكرونة قودي 500 غرام",
    "nameEn": "Goody Pasta 500g",
    "unitAr": "500 غرام",
    "unitEn": "500g",
    "price": 4.5,
    "marketPrice": 4.5,
    "emoji": "🍝",
    "imageUrl": "https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "bk_10",
    "categoryId": "bakery",
    "nameAr": "زيت زيتون فلسطين 1 لتر",
    "nameEn": "Palestine Olive Oil 1L",
    "unitAr": "1 لتر",
    "unitEn": "1 Liter",
    "price": 42.0,
    "marketPrice": 42.0,
    "emoji": "🫒",
    "imageUrl": "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "bk_11",
    "categoryId": "bakery",
    "nameAr": "زيت ذرة عافية 1.5 لتر",
    "nameEn": "Afia Corn Oil 1.5L",
    "unitAr": "1.5 لتر",
    "unitEn": "1.5 Liter",
    "price": 17.5,
    "marketPrice": 17.5,
    "emoji": "🍾",
    "imageUrl": "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "cn_1",
    "categoryId": "canned",
    "nameAr": "تونة قودي بالزيت 185 غرام",
    "nameEn": "Goody Tuna in Oil 185g",
    "unitAr": "185 غرام",
    "unitEn": "185g",
    "price": 6.5,
    "marketPrice": 6.5,
    "emoji": "🐟",
    "imageUrl": "https://images.unsplash.com/photo-1612886622686-23133f958f0d?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "cn_2",
    "categoryId": "canned",
    "nameAr": "تونة قودي بالماء 185 غرام",
    "nameEn": "Goody Tuna in Water 185g",
    "unitAr": "185 غرام",
    "unitEn": "185g",
    "price": 6.5,
    "marketPrice": 6.5,
    "emoji": "🐟",
    "imageUrl": "https://images.unsplash.com/photo-1612886622686-23133f958f0d?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "cn_3",
    "categoryId": "canned",
    "nameAr": "علبة فول مدمس الكسيح 400 غرام",
    "nameEn": "Kasih Fava Beans 400g",
    "unitAr": "400 غرام",
    "unitEn": "400g",
    "price": 4.5,
    "marketPrice": 4.5,
    "emoji": "🥫",
    "imageUrl": "https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "cn_4",
    "categoryId": "canned",
    "nameAr": "علبة حمص حب الكسيح 400 غرام",
    "nameEn": "Kasih Chickpeas 400g",
    "unitAr": "400 غرام",
    "unitEn": "400g",
    "price": 4.5,
    "marketPrice": 4.5,
    "emoji": "🥫",
    "imageUrl": "https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "cn_5",
    "categoryId": "canned",
    "nameAr": "ذرة حلوة قودي 340 غرام",
    "nameEn": "Goody Sweet Corn 340g",
    "unitAr": "340 غرام",
    "unitEn": "340g",
    "price": 5.5,
    "marketPrice": 5.5,
    "emoji": "🌽",
    "imageUrl": "https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "cn_6",
    "categoryId": "canned",
    "nameAr": "فطر مقطع قودي 400 غرام",
    "nameEn": "Goody Mushrooms 400g",
    "unitAr": "400 غرام",
    "unitEn": "400g",
    "price": 6.5,
    "marketPrice": 6.5,
    "emoji": "🍄",
    "imageUrl": "https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "cn_7",
    "categoryId": "canned",
    "nameAr": "معجون طماطم قودي 135 غرام",
    "nameEn": "Goody Tomato Paste 135g",
    "unitAr": "135 غرام",
    "unitEn": "135g",
    "price": 3.0,
    "marketPrice": 3.0,
    "emoji": "🥫",
    "imageUrl": "https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "cn_8",
    "categoryId": "canned",
    "nameAr": "زيتون أسود شرائح 350 غرام",
    "nameEn": "Sliced Black Olives 350g",
    "unitAr": "350 غرام",
    "unitEn": "350g",
    "price": 8.5,
    "marketPrice": 8.5,
    "emoji": "🫒",
    "imageUrl": "https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "cl_1",
    "categoryId": "cleaning",
    "nameAr": "مسحوق أرييل اتوماتيك 2.5 كغم",
    "nameEn": "Ariel Automatic 2.5kg",
    "unitAr": "2.5 كغم",
    "unitEn": "2.5 kg",
    "price": 35.0,
    "marketPrice": 35.0,
    "emoji": "🧼",
    "imageUrl": "https://images.unsplash.com/photo-1584813539806-2538b86923c4?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "cl_2",
    "categoryId": "cleaning",
    "nameAr": "مسحوق تايد اتوماتيك 2.5 كغم",
    "nameEn": "Tide Automatic 2.5kg",
    "unitAr": "2.5 كغم",
    "unitEn": "2.5 kg",
    "price": 32.0,
    "marketPrice": 32.0,
    "emoji": "🧼",
    "imageUrl": "https://images.unsplash.com/photo-1584813539806-2538b86923c4?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "cl_3",
    "categoryId": "cleaning",
    "nameAr": "سائل فيري بالليمون 1 لتر",
    "nameEn": "Fairy Lemon 1L",
    "unitAr": "1 لتر",
    "unitEn": "1 Liter",
    "price": 13.0,
    "marketPrice": 13.0,
    "emoji": "🧽",
    "imageUrl": "https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "cl_4",
    "categoryId": "cleaning",
    "nameAr": "مطهر ديتول 500 مل",
    "nameEn": "Dettol Liquid 500ml",
    "unitAr": "500 مل",
    "unitEn": "500ml",
    "price": 18.0,
    "marketPrice": 18.0,
    "emoji": "🧴",
    "imageUrl": "https://images.unsplash.com/photo-1584813539806-2538b86923c4?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "cl_5",
    "categoryId": "cleaning",
    "nameAr": "كلوركس مبيض ملابس 1 لتر",
    "nameEn": "Clorox Bleach 1L",
    "unitAr": "1 لتر",
    "unitEn": "1 Liter",
    "price": 7.5,
    "marketPrice": 7.5,
    "emoji": "🧼",
    "imageUrl": "https://images.unsplash.com/photo-1584813539806-2538b86923c4?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "cl_6",
    "categoryId": "cleaning",
    "nameAr": "مناديل فاين كلاسيك 5 علب",
    "nameEn": "Fine Tissues 5 Boxes",
    "unitAr": "5 علب",
    "unitEn": "5 Boxes",
    "price": 15.0,
    "marketPrice": 15.0,
    "emoji": "🧻",
    "imageUrl": "https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "cl_7",
    "categoryId": "cleaning",
    "nameAr": "ورق تواليت فاين 12 رول",
    "nameEn": "Fine Toilet Paper 12 Rolls",
    "unitAr": "12 رول",
    "unitEn": "12 Rolls",
    "price": 19.0,
    "marketPrice": 19.0,
    "emoji": "🧻",
    "imageUrl": "https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "cl_8",
    "categoryId": "cleaning",
    "nameAr": "شامبو بانتين 400 مل",
    "nameEn": "Pantene Shampoo 400ml",
    "unitAr": "400 مل",
    "unitEn": "400ml",
    "price": 16.5,
    "marketPrice": 16.5,
    "emoji": "🧴",
    "imageUrl": "https://images.unsplash.com/photo-1584813539806-2538b86923c4?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "cl_9",
    "categoryId": "cleaning",
    "nameAr": "صابون دوف 135 غرام",
    "nameEn": "Dove Soap 135g",
    "unitAr": "135 غرام",
    "unitEn": "135g",
    "price": 5.5,
    "marketPrice": 5.5,
    "emoji": "🧼",
    "imageUrl": "https://images.unsplash.com/photo-1584813539806-2538b86923c4?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "fr_1",
    "categoryId": "frozen",
    "nameAr": "ناجتس ساديا 500 غرام",
    "nameEn": "Sadia Nuggets 500g",
    "unitAr": "500 غرام",
    "unitEn": "500g",
    "price": 24.0,
    "marketPrice": 24.0,
    "emoji": "🍗",
    "imageUrl": "https://images.unsplash.com/photo-1562967914-608f82629710?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "fr_2",
    "categoryId": "frozen",
    "nameAr": "برجر نبيل بقري 1 كغم",
    "nameEn": "Nabil Beef Burger 1kg",
    "unitAr": "1 كغم",
    "unitEn": "1 kg",
    "price": 36.0,
    "marketPrice": 36.0,
    "emoji": "🍔",
    "imageUrl": "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "fr_3",
    "categoryId": "frozen",
    "nameAr": "برجر نبيل دجاج 1 كغم",
    "nameEn": "Nabil Chicken Burger 1kg",
    "unitAr": "1 كغم",
    "unitEn": "1 kg",
    "price": 34.0,
    "marketPrice": 34.0,
    "emoji": "🍔",
    "imageUrl": "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "fr_4",
    "categoryId": "frozen",
    "nameAr": "بطاطا لامب وستون 2.5 كغم",
    "nameEn": "Lamb Weston Fries 2.5kg",
    "unitAr": "2.5 كغم",
    "unitEn": "2.5 kg",
    "price": 20.0,
    "marketPrice": 20.0,
    "emoji": "🍟",
    "imageUrl": "https://images.unsplash.com/photo-1562967914-608f82629710?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "fr_5",
    "categoryId": "frozen",
    "nameAr": "كبة دجاج نبيل 500 غرام",
    "nameEn": "Nabil Chicken Kibbeh 500g",
    "unitAr": "500 غرام",
    "unitEn": "500g",
    "price": 22.0,
    "marketPrice": 22.0,
    "emoji": "🍗",
    "imageUrl": "https://images.unsplash.com/photo-1562967914-608f82629710?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  },
  {
    "id": "fr_6",
    "categoryId": "frozen",
    "nameAr": "بازيلاء مجمدة ساديا 400 غرام",
    "nameEn": "Sadia Frozen Peas 400g",
    "unitAr": "400 غرام",
    "unitEn": "400g",
    "price": 9.5,
    "marketPrice": 9.5,
    "emoji": "🥦",
    "imageUrl": "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",
    "lastSync": "سعر أساسي موثّق 🟢"
  }
];

const getDb = (req) => req.app.get('db');

// GET /api/mart_products — يرجع منتجات Firestore، وإلا القائمة الأساسية
router.get('/', async (req, res) => {
  try {
    const db = getDb(req);
    if (!db) return res.json(defaultMartProducts);
    const snapshot = await db.collection('mart_products').get();
    if (snapshot.empty) {
      return res.json(defaultMartProducts);
    }
    const products = [];
    snapshot.forEach(doc => products.push({ id: doc.id, ...doc.data() }));
    res.json(products);
  } catch (error) {
    console.error('mart_products GET error:', error.message);
    // عند أي خطأ رجّع الأساسية حتى لا تنكسر اللوحة
    res.json(defaultMartProducts);
  }
});

// POST /api/mart_products — إضافة/تحديث منتج (id ثابت = لا تكرار)
router.post('/', async (req, res) => {
  try {
    const db = getDb(req);
    if (!db) return res.status(503).json({ success: false, error: 'Database not connected' });
    const p = req.body || {};
    const id = p.id || ('prod_' + Date.now());
    await db.collection('mart_products').doc(String(id)).set({ ...p, id }, { merge: true });
    res.status(201).json({ success: true, id });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

// PATCH /api/mart_products/:id — تعديل (سعر/توفر...)
router.patch('/:id', async (req, res) => {
  try {
    const db = getDb(req);
    if (!db) return res.status(503).json({ success: false, error: 'Database not connected' });
    const ref = db.collection('mart_products').doc(String(req.params.id));
    if (!(await ref.get()).exists) {
      // لو المنتج من القائمة الأساسية ولسا مش بـ Firestore، أنشئه
      const base = defaultMartProducts.find(x => String(x.id) === String(req.params.id));
      if (base) { await ref.set({ ...base, ...req.body, id: base.id }); return res.json({ success: true, created: true }); }
      return res.status(404).json({ success: false, error: 'المنتج غير موجود' });
    }
    await ref.update(req.body || {});
    res.json({ success: true });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

// DELETE /api/mart_products/:id
router.delete('/:id', async (req, res) => {
  try {
    const db = getDb(req);
    if (!db) return res.status(503).json({ success: false, error: 'Database not connected' });
    await db.collection('mart_products').doc(String(req.params.id)).delete();
    res.json({ success: true });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

module.exports = router;
